sudo: required 
language: generic 
services: #ensure a copy of docker for travis actions 
  - docker

before_install: # some setup that needs to occur before we deploy our project
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t docker-flask . 
  - docker images
  - docker tag docker-flask $DOCKER_USERNAME/docker-flask
  - docker push $DOCKER_USERNAME/docker-flask
  - echo "BUILD WAS SUCCESSFUL"

script:  # contain all the needed commands that actually run our test suite 
     # - docker tag docker-flask sherifkunch/my-first-repo:latest
  - docker run -p 5000:5000 -e CI=true docker-flask 

#deploy:
#  provider: elasticbeanstalk
#  region: "eu-central-1"
#  app: "docker-flask"
#  env: "Dockerreact-env"
#  bucket_name: "elasticbeanstalk-eu-central-1-445589059283"
#  bucket_path: "docker-flask"
#  on:
#    branch: main
#  access_key_id: "$AWS_ACCESS_KEY"
#  secret_access_key:
#    secure: "$AWS_SECRET_KEY"