deployment:
        name: webapp
        image: sherifkunch/my-first-repo:flask-app-image
        tag: latest
        replicas: 1
        containerPort: 5000
service:
        name: flaskapp-lb-svc
        port: 5000
        targetPort: 5000
        type: NodePort
        nodePort: 30007