deployment:
        name: webapp
        #image: sherifkunch/my-first-repo:flask-app-image
        image: 392209090241.dkr.ecr.eu-central-1.amazonaws.com/dev/test:latest
        tag: latest
        replicas: 1
        containerPort: 5000
        imagePullSecrets: ecr-secret
service:
        name: flaskapp-lb-svc
        port: 5000
        targetPort: 5000
        type: NodePort
        nodePort: 30007
