name: Build, Test, and Push to Docker Hub
run-name: ${{ github.actor }} is running pipelines on GitHub Actions 🚀

on:
  push:
    branches:
      - main

jobs:
  building-my-first-container:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Build the Docker image
    - name: Build Docker image
      run: |
        IMAGE_TAG=${{ github.sha }}
        IMAGE_NAME=sherifkunch/jan16repositorydevopsdemonstrations
        docker build -t $IMAGE_NAME:$IMAGE_TAG .

    # Step 3: Push the Docker image to Docker Hub public registry
    - name: Push Docker image to Docker Hub
      run: |
        IMAGE_TAG=${{ github.sha }}
        IMAGE_NAME=ysherifkunch/jan16repositorydevopsdemonstrations
        docker push $IMAGE_NAME:$IMAGE_TAG
